---
title:  Biol/Math 218 pop quiz 1
author: Your Name Here
output:
  rmdformats::downcute:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    downcute_theme: "chaos"
    toc_depth: 3
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "pop_quiz_html"
    )
  })
---

## Introduction

A colleague is interested in testing if
knocking down (disabling) a particular gene impacts
wing length in *Drosophila melanogaster*, common fruit flies.
However, she does not know the natural frequency of *Drosophila* 
wing lengths. To determine this, she measured the wing lengths
of 60 flies (30 male and 30 female).

Her data is provided in `flies.csv`, but she does not
know how to use R.

## Part 01
In the space below, provide a code block that will 

1. Import the data file
2. Produce a properly labelled plot(s) to display the frequencies of the wing lengths in the sample

```{r}
``` 

## Part 02
Below, describe the figure, including the shape of the plot, the distribution 
of wing lengths and the most common wing length(s) in her sample. 

Also, are there any important patterns in the frequency data? If so, provide a biologically
relevant cause of the patterns in the data.

## Answer: